version: '3'
services:
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: <ip-domain-db>
      DATABASE_PORT: 5432
      DATABASE_NAME: <db-name>
      DATABASE_PASSWORD: <db-password>
      APPLICATION_PORT: 8080

  database:
    image: postgres:14.2
    environment:
      POSTGRES_DB: <db-name>
      POSTGRES_PASSWORD: <db-password>
    ports:
      - "5432:5432"

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports:
      - "80:80"
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
